### ISSUE TITLE
Example app error 

### ISSUE THREAD

**Issue by escottgoodwin** [BrutalCoding/aub.ai#6]
cloned repo and did pub get. flutter run

Lexical or Preprocessor Issue (Xcode): 'llama.cpp/llama.h' file not found

Is this something we need to download?

**Comment by BrutalCoding** [comment]
Hi @escottgoodwin,

Besides a `git clone ...etc`, you'd need to execute `git submodule update --remote`. This is because there are 2 git submodules added which otherwise wouldn't get pulled too.

I've helped someone out yesterday with the same issue and I wrote down the steps in detail in this comment: https://github.com/BrutalCoding/aub.ai/issues/5#issuecomment-1861500462

Let me know if this helped so I can close this ticket if this comment resolved it for you too.

I will clear this confusion up in the README next time.

Cheers,
Daniel

**Comment by escottgoodwin** [comment]
I was able to do it manually (the second option in comment #5. Thanks.

**Comment by BrutalCoding** [comment]
> I was able to do it manually (the second option in comment #5. Thanks.

That's good to hear. I'm glad the issue has been resolved for you.

This git submodule step is a bit of weird, I have to admit. A person would expect to just run git clone (or downloading the repo zip file) and being able to run it out of the box. This 'hidden' second step, the git submodule command, is not intuitive IMO.

Nothing personal to you btw, just a random thought of mine. I'll keep an eye out on other approaches.

Closing this ticket now.
